---
- name: Install Docker
  hosts: localhost
  become: true
  tasks:
  - import_role:
      name: nickjj.docker
    vars:    
      docker_version: "18.05.0"

- name: Spin up mysql-cluster
  hosts: localhost
  become: true
  roles:
  - docker-mysql-cluster
  tags:
    mysql-cluster
