---

- name: Create docker network
  command: docker network create mysql-cluster --subnet=10.0.0.0/16 || true

- name: Create mysql-cluster management node
  command: docker run -d --net=mysql-cluster --name=mysql-mgmt --ip=10.0.0.11 mysql/mysql-cluster ndb_mgmd

- name: Create mysql-cluster data node
  command: docker run -d --net=mysql-cluster --name=mysql-data1 --ip=10.0.0.12 mysql/mysql-cluster ndbd

- name: Create mysql-cluster data node
  command: docker run -d --net=mysql-cluster --name=mysql-data2 --ip=10.0.0.13 mysql/mysql-cluster ndbd

- name: Create mysql-cluster server node
  command: docker run -d --net=mysql-cluster --name=mysql-srv1 --ip=10.0.0.1 -e MYSQL_ROOT_PASSWORD="123456" mysql/mysql-cluster mysqld
